version: '2'
services:
  mysql:  
    image: mysql:5.5
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mysql
    environment:
      RAILS_ENV: development
    command: ["rails", "s", "-b", "0.0.0.0"]